/**
 * generated by Xtext
 */
package org.eclipse.xtext.example.fowlerdsl.validation;

import org.eclipse.xtext.example.fowlerdsl.statemachine.StatemachinePackage;
import org.eclipse.xtext.example.fowlerdsl.validation.AbstractStatemachineValidator;
import org.eclipse.xtext.validation.Check;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class StatemachineValidator extends AbstractStatemachineValidator {
  public final static String INVALID_NAME = "invalidName";
  
  @Check
  public void checkStateStartsWithCapital(final org.eclipse.xtext.example.fowlerdsl.statemachine.State state) {
    boolean _isUpperCase = Character.isUpperCase(state.getName().charAt(0));
    if (_isUpperCase) {
      this.warning("Name should start with an lower case letter", StatemachinePackage.Literals.STATE__NAME, 
        StatemachineValidator.INVALID_NAME, state.getName());
    }
  }
}
