/**
 * generated by Xtext
 */
package org.eclipse.xtext.example.fowlerdsl.validation;

import org.eclipse.xtext.example.fowlerdsl.validation.AbstractStatemachineValidator;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;
import org.eclipse.xtext.validation.Check;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class StatemachineValidator extends AbstractStatemachineValidator {
  public final static String INVALID_NAME = "invalidName";
  
  @Check
  public Object checkGreetingStartsWithCapital(final AbstractDeclarativeValidator.State state) {
    return null;
  }
}
