/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.fowlerdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.example.fowlerdsl.ui.findrefs.StatemachineReferenceFinder;
import org.eclipse.xtext.example.fowlerdsl.ui.rename.StatemachineDependentElementsCalculator;
import org.eclipse.xtext.example.fowlerdsl.ui.rename.StatemachineReferenceUpdaterDispatcher;
import org.eclipse.xtext.ui.editor.findrefs.IReferenceFinder;
import org.eclipse.xtext.ui.refactoring.IDependentElementsCalculator;
import org.eclipse.xtext.ui.refactoring.impl.ReferenceUpdaterDispatcher;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StatemachineUiModule extends org.eclipse.xtext.example.fowlerdsl.ui.AbstractStatemachineUiModule {
	public StatemachineUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends ReferenceUpdaterDispatcher> bindReferenceUpdaterDispatcher() {
		return StatemachineReferenceUpdaterDispatcher.class;
	}
	
	public Class<? extends IReferenceFinder>  bindIReferenceFinder() {
		return StatemachineReferenceFinder.class;
	}
	
	public Class<? extends IDependentElementsCalculator> bindIDependentElementsCalculator() {
		return StatemachineDependentElementsCalculator.class;
	}
}
